apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: dev
  labels:
    app: api-service
    managed-by: plate
    runtime: go
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
        managed-by: plate
        runtime: go
        environment: development
    spec:
      containers:
      - name: api-service
        image: httpd:2.4-alpine
        ports:
        - containerPort: 80
        env:
        - name: GO_ENV
          value: "development"
        - name: DB_HOST
          value: "postgres-service"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: dev
  labels:
    app: api-service
    managed-by: plate
spec:
  selector:
    app: api-service
  ports:
  - port: 3000
    targetPort: 80
    name: http
  type: ClusterIP