apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
  namespace: dev
  labels:
    app: data-processor
    managed-by: plate
    runtime: python
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
        managed-by: plate
        runtime: python
        environment: development
    spec:
      containers:
      - name: data-processor
        image: python:3.9-alpine
        command: ["python", "-c", "import time; print('Data processor running...'); time.sleep(3600)"]
        env:
        - name: PYTHON_ENV
          value: "development"
        - name: WORKERS
          value: "2"
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
# Let's also create a failed deployment to show different statuses
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: dev
  labels:
    app: worker-service
    managed-by: plate
    runtime: go
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
        managed-by: plate
        runtime: go
        environment: development
    spec:
      containers:
      - name: worker-service
        image: busybox:1.35
        command: ["sh", "-c", "echo 'Worker starting...'; sleep 10; echo 'Worker failed'; exit 1"]
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "25m"